### ISSUE TITLE
helm chart should not default image tag to latest

### ISSUE THREAD

**Issue by not22day** [stackitcloud/stackit-cert-manager-webhook#48]
### What happened?

The current Chart YAML looks like this

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: stackit-cert-manager-webhook
version: 0.3.0

I understand Helm best practices would be
1) appVersion becomes the software release version = the tag of the docker image
2) version is the version of the helm chart enumerated and incremented by itself

image tag gets defaulted by appVersion 
image: "{{ $registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

### How can we reproduce this?

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slm0n87** [comment]
Thank you @not22day  reporting the issue!  
The problem should be resolved with the changes in the linked PR and the release of Helmchart version [stackit-cert-manager-webhook-0.3.3](https://github.com/stackitcloud/stackit-cert-manager-webhook/releases/tag/stackit-cert-manager-webhook-0.3.3).  
Please feel free to test it and let us know if you encounter any further issues. We appreciate your feedback!

**Comment by not22day** [comment]
Thanks for the fix - works as expected now
