### ISSUE TITLE
imagePullSecrets missing as a value

### ISSUE THREAD

**Issue by docbyte86** [stackitcloud/stackit-cert-manager-webhook#71]
### Is your feature request related to a problem? Please describe.

There is no option to add a secret if we want to pull the image from a private container repository.
Is it possible to add that as a value?

### Describe the solution you'd like

I want to point global.imagePullSecrets to a secret to pull the images.

### Describe alternatives you've considered

n/a

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slm0n87** [comment]
Hi @docbyte86 - thx for the report. I add a new array "imagePullSecrets" to the chard in the linked PR.

**Comment by slm0n87** [comment]
The problem should be resolved with the release of Helmchart version [stackit-cert-manager-webhook-0.3.5](https://github.com/stackitcloud/stackit-cert-manager-webhook/releases/tag/stackit-cert-manager-webhook-0.3.5).
After upgrading the chart you can reference the secret by:
```
imagePullSecrets:
  - name: private-registry-secret
```
or by command line via `--set imagePullSecrets[0].name=private-registry-secret`, where "private-registry-secret" is the name of you secret locate in the same namespace.

Please feel free to test it and let us know if you encounter any further issues. We appreciate your feedback!

**Comment by docbyte86** [comment]
it works. thank you very much for the fast response!
